[package]
name = "alltheplaces"
version = "0.1.0"
edition = "2021"

[dependencies]
geojson = "0.24.2"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["blocking"] }
serde = "1.0.218"
serde_json = "1.0.140"
walkdir = "2.5.0"
zip = "2.2.3"
zip-extensions = "0.8.1"
