services:
  postgres:
    image: postgis/postgis:17-3.5-alpine
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: poi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d poi"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pg_data:
